version: '3'

services:
  pythonuserservice:
    container_name: pythonuserservice
    build: 
      context: .
    restart: always
    ports:
      - "8000:5000"
    volumes:
      - ./:/app
    networks:
      - mysql-python-app-network
    depends_on:
      - dockerdbhost

  dockerdbhost:
    container_name: dockerdbhost
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd@123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql 
    networks:
      - mysql-python-app-network

networks:
  mysql-python-app-network:
    name: mysql-python-app-network

volumes:
  mysql-data:
